spring:
  cache: 
    type: redis
  redis: 
    host: localhost
    port: 6379
    timeOfLife: 600000
  data:
    mongodb:
      database: coderhouse
      host: localhost
      port: 27017
  mail:
    config: andres.bravo161@gmail.com
    host: smtp.gmail.com
    port: 587
    username: coderhouse.ecommerce@gmail.com
    password: uwtyrrtivzncqrun
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

jwt:
  expiration: 1200000
  secret: coderhouseecommerce

server:
  port: 8080

