spring:
  cache: 
    type: redis
  redis: 
    host: localhost
    port: 6379
    timeOfLife: 600000
  data:
    mongodb:
      database: coderhouse
      host: localhost
      port: 27017

jwt:
  expiration: 1200000
  secret: coderhouseecommerce


server:
  port: 8080
